spring:
  application:
    name: SpringBootMicroServiceClient
    
#discovery servcr access

eureka:
  client:
    service-url:
      deafaultZone: http://localhost:1111/eureka/

      
server:
  port: 7799